# ./discord-radio-bot-modular/docker-compose.yml

version: '3.8'

services:
  yuzu:
    build: .
    container_name: yuzu-discord-bot
    restart: unless-stopped
    env_file:
      - .env
    
    volumes:
      # This maps the './data' folder on your host machine
      # to the '/app/data' folder inside the container.
      # The bot's code lives in /app, and it writes data to /app/data.
      # This keeps the data separate from the code inside the container.
      - ./data:/app/data
      # - ./logs:/app/logs